require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Paws' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'PawsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'Paws-tvOS' do
  # Pods for Paws-tvOS

  target 'Paws-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
